let number = 10;
let nome = "Bernardo";
let bool = true;
let arr = [];
number = 20;
nome = "jotinha";
bool = false;
arr = [1, 2, 3];
console.log(number, nome, bool, arr);
console.log(typeof number);
console.log(typeof nome);
console.log(typeof bool);
console.log(typeof arr);
