let fruta = ["amora", "ameixa", "abacate"];
fruta.push("banana", "bergamota");
fruta.length;
console.log(fruta);
console.log(fruta.length);
let some1 = fruta.shift();
let some2 = fruta.shift();
let some3 = fruta.shift();
console.log(some1, some2, some3);
console.log(fruta);
